version: '3.7'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - BACKEND_PORT=$BACKEND_PORT
      - MONGO_DB=$MONGO_DB
    # Add volumnes
    volumes:
      # NOT in production
      # Inside container
      - /backend/node_modules
      # Outside container
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - stock

  db:
    container_name: db
    restart: always
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - stock

  nginx:
    container_name: ngnix
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - stock

  
volumes:
  mongo_data:
    
networks:
  stock: