version: "3.7"
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: .env.prod
    environment:
      - BACKEND_PORT=$BACKEND_PORT
      - MONGO_DB=$MONGO_DB
      - REDIS_DB=$REDIS_DB
      - REDIS_STOCK_TIME=$REDIS_STOCK_TIME
      - NINE_STOCK_TIME=$NINE_STOCK_TIME
      - INPUT_STOCK_TIME=$INPUT_STOCK_TIME
      - FRONTEND=$FRONTEND

    # Add volumnes
    volumes:
      # NOT in production
      # Inside container
      - /backend/node_modules
      # Outside container
      # ./backend is local machine : /backend is in the docker
      - ./backend:/backend
      # - backend_data:/backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo_db
      - redis_db
    networks:
      - api

  redis_db:
    container_name: redis_db
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - ./data/redis:/data
      # - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - api

  mongo_db:
    container_name: mongo_db
    restart: always
    image: mongo
    volumes:
      - ./data/mongo_db:/data/db
      # - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - api

  cadvisor:
    container_name: cadvisor
    restart: always
    image: google/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis_db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    #  - /Users/jayjo/Desktop/certs:/etc/nginx/certs
    ## Source volumes to Target volumes

    depends_on:
      - backend
    networks:
      - api

# volumes:
#   backend_data:
#   redis_data:
#   mongo_data:

networks:
  api:
