version: '3.7'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - BACKEND_PORT=$BACKEND_PORT
      - MONGO_DB=$MONGO_DB
    # Add volumnes
    volumes:
      # NOT in production
      # Inside container
      - /backend/node_modules
      # Outside container
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - api

  db:
    container_name: db
    restart: always
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - api

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes: 
     - ./nginx/certs:/etc/nginx/certs
    #  - /Users/jayjo/Desktop/certs:/etc/nginx/certs
     ## Source volumes to Target volumes

    depends_on:
      - backend
    networks:
      - api
  
volumes:
  mongo_data:
    
networks:
  api: